# A service which exposes the cog srv text analytics language api container through a dependable hostname: http://language:5000
apiVersion: v1
kind: Service
metadata:
  name: language
  labels:
    run: language
spec:
  selector:
    app: language
  type: LoadBalancer
  ports:
  - name: language
    port: 5000
    targetPort: 5000
    protocol: TCP
---
# A deployment declaratively indicating how many instances of the .net frontend app container we want up
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: language
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: language
    spec:
      containers:
      - name: language
        image: diberrycontainerregistry001.azurecr.io/language:latest
        ports:
        - name: public-port
          containerPort: 5000
        livenessProbe:
          httpGet:
            path: /status
            port: public-port
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
        args:
            - "Eula=accept"
            - "ApiKey=6fa5dc75f09b482c9826be2f4551af4aaz" # < API Key for the Language Service >
            - "Billing=https://westus.api.cognitive.microsoft.com/text/analytics/v2.0" # < Language billing endpoint URI >
            - "Logging:Console:LogLevel:Default=Information"
        volumeMounts:
          - name: azure
            mountPath: /output
      volumes:
      - name: azure
        azureFile:
          secretName: azure-secret
          shareName: aksshare
          readOnly: false
      imagePullSecrets:
        - name: ntRFwOFd9AOmcEUvpOdTEMPwN6D/hTAS # < Name of the registry secret providing access to the frontend image >
      automountServiceAccountToken: false

